---
- include: el7/main.yml
  when: ansible_os_family == "RedHat" 
        and ansible_distribution_major_version|int >= 7

- include: el6/main.yml
  when: ansible_os_family == "RedHat" 
        and ansible_distribution_major_version|int >=6
        and ansible_distribution_major_version|int <7