---
# tasks file for centos-7-security
- include: yum.yml
  when: security_yum_verify_gpg == True

- include: aide.yml
  when: security_aide_configure == True

- include: mounts.yml
  when: security_mounts_configure == True

- include: modules.yml
  when: security_module_blacklist_configure == True

- include: authentication.yml
  when: security_authentication_configure == True

- include: kernel_settings.yml
  when: security_kernel_settings_configure == True

- include: audit.yml
  when: security_audit_configure == True

- include: rsyslog.yml
  when: security_rsyslog_configure == True

- include: sshd.yml
  when: security_sshd_configure == True

- include: grub.yml
  when: security_grub_configure == True

- include: miscellaneous.yml
