---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: vars

- include: el7/main.yml
  when: ansible_os_family == "RedHat"
        and ansible_distribution_major_version|int == 7

- include: el6/main.yml
  when: ansible_os_family == "RedHat"
        and ansible_distribution_major_version|int == 6
