---
# handlers file for centos-7-security
- name: reload sysctl
  shell: sysctl -p /etc/sysctl.conf
  tags:
    - skip_ansible_lint

- name: dconf update
  shell: dconf update
  tags:
    - skip_ansible_lint

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
