---
# handlers file for centos-7-security
- name: reload sysctl
  shell: sysctl -p /etc/sysctl.conf
  tags:
    - skip_ansible_lint

- name: dconf update
  shell: dconf update
  tags:
    - skip_ansible_lint

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ntp
  service:
    name: ntpd
    state: restarted

- name: save iptables
  shell: service iptables save

- name: save ip6tables
  shell: service ip6tables save