---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos7-disa-stig
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: testinfra
  lint:
    name: flake8
