---
- name: Ensure audit packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "audit"
    - "audispd-plugins"

- name: Ensure sendmail is installed
  package:
    name: sendmail
    state: present
  when: security_audit_space_left_action == 'email'

- name: Configure audispd
  template:
    src: "templates/el{{ ansible_distribution_major_version }}/{{ item.split('/')[-1] }}.j2"
    dest: "{{ item }}"
  with_items: "{{ security_audit_audispd_configuration_files }}"
  when: security_audit_audisp_configure == True

- name: Configure audit rules
  template:
    dest: "{{ security_audit_configuration_file_path }}"
    src: templates/common/audit.rules.j2

- name: Configure auditd.conf
  template:
    dest: /etc/audit/auditd.conf
    src: templates/common/auditd.conf.j2

- name: Check kernel arguments
  shell: |
    kernel_args=$(/sbin/grubby --info=ALL | grep args)
    cut -d '=' -f2- <<< "$kernel_args"
  register: kernel_args
  changed_when: False
  tags:
    - skip_ansible_lint

- name: Enable auditing for processes which start prior to the audit daemon"
  shell: /sbin/grubby --update-kernel=ALL --args="audit=1"
  failed_when: False
  when: "'audit=1' not in kernel_args.stdout"
  tags:
    - skip_ansible_lint

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: True
