---
- name: Ensure SSHD is installed
  package:
    name: openssh-server
    state: installed

- name: Configure sshd
  template:
    dest: /etc/ssh/sshd_config
    src: templates/common/sshd_config.j2
  notify: restart sshd

- name: Fix SSH host key permissions
  file:
    path: "/etc/ssh/{{ item }}"
    mode: 0600
  with_items: "{{ security_sshd_default_host_keys }}"

- name: Ensure firewall port is opened
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  when: ansible_distribution_major_version == '7'

- name: Ensure firewall port is opened
  iptables:
    chain: "INPUT"
    jump: "ACCEPT"
    protocol: tcp
    destination_port: 22
  when: ansible_distribution_major_version == '6'
  notify: save iptables

- name: Enable sshd service
  service:
    name: sshd
    enabled: True
