---
- name: Disable GDM automatic and guest login
  template:
    src: templates/custom.conf.j2
    dest: /etc/gdm/custom.conf

- name: Configure GNOME security settings
  template:
    src: templates/00-security-settings.j2
    dest: /etc/dconf/db/local.d/10-scap-security-guide
  notify: dconf update

- name: Configure GDM Banners
  template:
    src: templates/00-security-settings-gdm.j2
    dest: /etc/dconf/db/gdm.d/00-security-settings
  notify: dconf update

- name: Configure GNOME security locks
  copy:
    src: files/00-security-settings-lock
    dest: /etc/dconf/db/local.d/locks/00-security-settings-lock
  notify: dconf update

- name: Configure GDM locks
  copy:
    src: files/00-security-settings-lock-gdm
    dest: /etc/dconf/db/gdm.d/locks/00-security-settings-lock
  notify: dconf update

- name: Ensure symlinks are in place
  file:
    src: /etc/dconf/db/local.d/10-scap-security-guide
    dest: "{{ item }}"
    state: link
  with_items:
    - "/etc/dconf/db/local.d/00-disable-CAD"
    - "/etc/dconf/db/local.d/01-banner-message"
  when: centos_7_security_scanner == 'nessus'

- name: Ensure symlinks are in place
  file:
    src: /etc/dconf/db/gdm.d/00-security-settings
    dest: "{{ item }}"
    state: link
  with_items:
    - "/etc/dconf/db/gdm.d/01-banner-message"
