---
- name: Install screen
  package:
    name: screen
    state: installed
  when: security_screen == True

- name: Disable ctrl-alt-del reboot activation
  systemd:
    name: "ctrl-alt-del.target"
    masked: yes
  when: security_ctrl_alt_del == True

- name: Configure the login banner
  template:
    dest: /etc/issue
    src: templates/common/issue.j2
  when: security_login_banner == True

- name: Disable kdump service
  service:
    name: kdump
    state: stopped
    enabled: False
  failed_when: False
  when: security_disable_kdump == True

- name: Enable cron service
  service:
    name: crond
    state: started
    enabled: True
  when: security_disable_cron == False

- name: Disable prelinking
  lineinfile:
    create: True
    path: /etc/sysconfig/prelink
    regexp: '^PRELINKING='
    line: 'PRELINKING=no'
  when: security_disable_prelinking == True

- name: Ensure SELinux is not disabled in grub
  replace:
    dest: /etc/default/grub
    regexp: selinux=0
  when: security_selinux_configure == True

- name: Enable SELinux
  selinux:
    state: enforcing
    policy: targeted
  when: security_selinux_configure == True

- name: Prevent unrestricted mail relaying
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_client_restrictions'
    line: 'smtpd_client_restrictions = permit_my_networks,reject'
  when: security_postfix_restrict_relaying == True
