---
- name: Ensure kernel modules are disabled
  template:
    dest: /etc/modprobe.d/disa_stig_blacklist.conf
    src: templates/disa_stig_blacklist.conf.j2

- name: Ensure symlinks are created
  file:
    src: /etc/modprobe.d/disa_stig_blacklist.conf
    dest: /etc/modprobe.d/nousbstorage
    state: link
  when: centos_7_security_scanner == 'nessus'
