---
- name: Ensure SSHD is installed
  package:
    name: openssh-server
    state: installed

- name: Configure sshd
  template:
    dest: /etc/ssh/sshd_config
    src: templates/sshd_config.j2
  notify: restart sshd

- name: Fix SSH host key permissions
  file:
    path: "/etc/ssh/{{ item }}"
    mode: 0600
  with_items:
    - "ssh_host_ecdsa_key"
    - "ssh_host_ed25519_key"
    - "ssh_host_rsa_key"

- name: Ensure firewalld port is opened
  firewalld:
    service: ssh
    permanent: true
    state: enabled

- name: Enable sshd service
  service:
    name: sshd
    state: started
    enabled: True
